### ISSUE TITLE
Getting an error from aiohttp.py when installing with pip

### ISSUE THREAD

**Issue by chipkellam** [pusher/pusher-http-python#52] opened 2015-05-14 19:59 UTC
Python version: 2.7.3

Issued: pip install pusher==1.1.3

Error:

```
Installing collected packages: pusher
  Running setup.py install for pusher
    SyntaxError: ('invalid syntax', ('[REDACTED]/python2.7/site-packages/pusher/aiohttp.py', 24, 29, '        response = yield from asyncio.wait_for(\n'))

```

**Comment by zimbatm** [comment] 2015-05-14 22:39
@jpatel531 looks like we're still having issues with python 3.0 aio :/ I wonder why pip tries to load that file.

**Comment by jpatel531** [comment] 2015-05-16 14:39
i'm not too sure either - it seems to be working fine on different machines and version i use. i'll look into it

**Comment by zimbatm** [comment] 2015-05-18 16:19
With python 2.6.7:
```
$ pip install pusher
Downloading/unpacking pusher
  Downloading pusher-1.1.3-py2-none-any.whl
Downloading/unpacking requests>=2.3.0 (from pusher)
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB): 470kB downloaded
Downloading/unpacking six (from pusher)
  Downloading six-1.9.0-py2.py3-none-any.whl
Installing collected packages: pusher, requests, six
Compiling /Users/zimbatm/code/github.com/pusher/pusher-http-python/.direnv/python-2.6.7/build/pusher/pusher/aiohttp.py ...
SyntaxError: ('invalid syntax', ('/Users/zimbatm/code/github.com/pusher/pusher-http-python/.direnv/python-2.6.7/build/pusher/pusher/aiohttp.py', 24, 29, '        response = yield from asyncio.wait_for(\n'))

Successfully installed pusher requests six
Cleaning up...
```

**Comment by zimbatm** [comment] 2015-05-18 16:22
@chipkellam can you give us your version of pip ?

**Comment by chipkellam** [comment] 2015-05-18 18:27
Currently using v1.5.2.



On May 18, 2015 at 12:22:40 PM, zimbatm (notifications@github.com) wrote:

@chipkellam can you give us your version of pip ?

**Comment by zimbatm** [comment] 2015-05-18 18:35
Same, I had missed that too previously. I suppose pip is pre-compiling all the python code in the repo and hitting that file at some point. I'm not really sure how we could work around the issue without separating the file into a different package.

**Comment by jpatel531** [comment] 2015-05-18 21:41
@zimbatm - would it be too hacky to rescue the error for python versions < 3 ? otherwise i think separating out *might* be the way to go

**Comment by jpatel531** [comment] 2015-05-28 23:28
This looks like a duplicate of https://github.com/benoitc/gunicorn/issues/788 , https://github.com/benoitc/gunicorn/issues/810 , and https://github.com/benoitc/gunicorn/issues/871

It might need an upgrade to the latest version of pip. I'll make a note about this on the README

**Closed** 2018-07-16 16:37 UTC
Labels: Known issue
