### ISSUE TITLE
Refactor Code

### ISSUE THREAD

**Issue by kailashchoudhary11** [pusher/pusher-http-python#188] opened 2022-10-15 03:00 UTC
Using .format method or f strings will be better than using the % formatting for strings.

**Comment by sonologico** [comment] 2022-10-16 06:52
Thanks for the suggestion. You're right. It would indeed be better. I'll close this issue since it's not a bug. Feel free to send a PR if you have the time and we don't get to it before you do.

**Closed by sonologico** 2022-10-16 06:52 UTC

**Comment by kailashchoudhary11** [comment] 2022-10-16 07:09
@sonologico  Should I use fstrings or .format cause fstrings isn't supported by python < 3.7 I guess.

**Comment by sonologico** [comment] 2022-10-16 07:15
`.format` is the one that is present in all the versions we support, so I would got for that.
